// SPDX-License-Identifier: MIT
// Copyright (c) 2026 Hiroki Kawakami
// Generates the cross-language golden fixtures consumed by the C++ host tests:
//   components/namecard_pdf/test/fixtures/*.pdf
//   components/namecard_pdf/test/fixtures/manifest.json
//
// The TS writer is the source of truth; the C++ parser must reproduce these
// exact bytes/offsets. Run: npm run gen-fixtures (from editor/).

import { createHash } from "node:crypto";
import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import {
  buildNameCardPdf,
  buildSharePdf,
  parseFooter,
  type NameCardInput,
} from "./index.ts";
import type { GlyphSet } from "./glyphs.ts";
import { GLYPH_PX } from "./constants.ts";

const here = dirname(fileURLToPath(import.meta.url));
const testDir = join(here, "../../../../components/namecard_pdf/test");
const assetsDir = join(testDir, "assets");
const outDir = join(testDir, "fixtures");

const asset = (name: string) =>
  new Uint8Array(readFileSync(join(assetsDir, name)));
const sha256 = (b: Uint8Array) => createHash("sha256").update(b).digest("hex");

// A tiny synthetic glyph set (no canvas in node): two 6x8 glyphs so the C++
// side exercises the name_glyphs blob + RLE decode path.
function syntheticGlyphs(): GlyphSet {
  const mk = (codepoint: number, rows: string[]) => {
    const boxW = rows[0].length;
    const boxH = rows.length;
    const bits = new Uint8Array((boxW * boxH + 7) >> 3);
    let i = 0;
    for (const r of rows)
      for (const ch of r) {
        if (ch === "#") bits[i >> 3] |= 0x80 >> (i & 7);
        i++;
      }
    return { codepoint, advW: boxW * 16, boxW, boxH, ofsX: 0, ofsY: 0, bits };
  };
  return {
    glyphPx: GLYPH_PX,
    baseLine: Math.round(GLYPH_PX * 0.8),
    lineHeight: Math.round(GLYPH_PX * 1.17),
    glyphs: [
      mk(0x9b3c, [
        "..##..",
        ".#..#.",
        "######",
        "#....#",
        "#....#",
        "#....#",
        "#....#",
        "......",
      ]),
      mk(0x4e9c, [
        "######",
        "...#..",
        "..#...",
        ".####.",
        "#....#",
        "#....#",
        ".####.",
        "......",
      ]),
    ],
  };
}

interface Fixture {
  id: string;
  input: NameCardInput;
}

const fixtures: Fixture[] = [
  {
    id: "basic",
    input: {
      name: "山田太郎",
      url: "https://example.com/yamada",
      message: "はじめまして。よろしくお願いします。",
      display: asset("display.jpg"),
      shares: [asset("share1.jpg"), asset("share2.jpg")],
    },
  },
  {
    id: "glyphs",
    input: {
      name: "鬛亜",
      url: "https://example.com/rare",
      message: "難しい漢字のテスト",
      display: asset("display.jpg"),
      shares: [asset("share1.jpg")],
      nameGlyphs: syntheticGlyphs(),
    },
  },
];

mkdirSync(outDir, { recursive: true });

const results = fixtures.map(({ id, input }) => {
  const full = buildNameCardPdf(input);
  const share = buildSharePdf(input);
  const fullName = `${id}.mnc.pdf`; // my name card (display + share)
  const shareName = `${id}.snc.pdf`; // shared name card (share data only)
  writeFileSync(join(outDir, fullName), full);
  writeFileSync(join(outDir, shareName), share);

  const { entries, baseTotalLength } = parseFooter(full);
  // sanity: share == truncated full
  if (
    Buffer.compare(
      Buffer.from(full.subarray(0, baseTotalLength)),
      Buffer.from(share),
    ) !== 0
  ) {
    throw new Error(`${id}: share != truncated full`);
  }

  return {
    id,
    full: fullName,
    share: shareName,
    name: input.name,
    url: input.url,
    message: input.message,
    baseTotalLength,
    assets: entries.map((e) => ({
      type: e.type,
      flags: e.flags,
      subtype: e.subtype,
      offset: e.offset,
      length: e.length,
      crc32: e.crc,
      sha256: sha256(full.subarray(e.offset, e.offset + e.length)),
    })),
  };
});

const manifest = {
  note: "Generated by editor gen-fixtures.ts — do not edit. Golden for C++ host tests.",
  fixtures: results,
};
writeFileSync(
  join(outDir, "manifest.json"),
  JSON.stringify(manifest, null, 2) + "\n",
);

// Also emit a C header so the host test needs no JSON parser (cf. jpeg_fixtures.h).
const cstr = (s: string) =>
  '"' + s.replace(/\\/g, "\\\\").replace(/"/g, '\\"') + '"';
const h: string[] = [
  "/* Generated by editor gen-fixtures.ts — do not edit. Golden for the host test. */",
  "#pragma once",
  "#include <cstdint>",
  "",
  "struct NckFixAsset { uint8_t type, flags, subtype; uint32_t offset, length, crc32; };",
  "struct NckFixture { const char *full; const char *share; const char *name; const char *url;",
  "                    const char *message; uint32_t base_total_length; int n_assets;",
  "                    const NckFixAsset *assets; };",
  "",
];
for (const r of results) {
  h.push(`static const NckFixAsset kFix_${r.id}_assets[] = {`);
  for (const a of r.assets) {
    h.push(
      `    {${a.type}, ${a.flags}, ${a.subtype}, ${a.offset}, ${a.length}, 0x${a.crc32.toString(16)}u},`,
    );
  }
  h.push("};");
}
h.push("", "static const NckFixture kNckFixtures[] = {");
for (const r of results) {
  h.push(
    `    {${cstr(r.full)}, ${cstr(r.share)}, ${cstr(r.name)}, ${cstr(r.url)}, ${cstr(r.message)}, ` +
      `${r.baseTotalLength}u, ${r.assets.length}, kFix_${r.id}_assets},`,
  );
}
h.push("};", `static const int kNckFixtureCount = ${results.length};`, "");
writeFileSync(join(outDir, "manifest.h"), h.join("\n"));

console.log(`wrote ${results.length} fixtures to ${outDir}`);
