/*
 * SPDX-License-Identifier: MIT
 * Copyright (c) 2026 Hiroki Kawakami
 *
 * Host unit test for namecard_pdf (g++, no ESP-IDF, ASAN/UBSAN). Validates the
 * parser against the golden fixtures generated by the TypeScript writer
 * (fixtures/manifest.h). Run via run.sh; pass the fixtures dir as argv[1].
 */

#include <cstdint>
#include <cstdio>
#include <cstring>
#include <string>
#include <vector>

#include "fixtures/manifest.h"
#include "namecard_pdf.hpp"

using namespace nckpdf;

static int failures = 0;
#define CHECK(cond, msg)                                                            \
    do {                                                                            \
        if (!(cond)) {                                                              \
            printf("FAIL: %s (%s:%d)\n", msg, __FILE__, __LINE__);                  \
            failures++;                                                             \
        }                                                                           \
    } while (0)

static std::string g_dir;

static std::string path(const char *name) { return g_dir + "/" + name; }

static std::vector<uint8_t> read_file(const std::string &p) {
    std::vector<uint8_t> out;
    FILE *f = fopen(p.c_str(), "rb");
    if (!f) return out;
    fseek(f, 0, SEEK_END);
    long n = ftell(f);
    fseek(f, 0, SEEK_SET);
    out.resize(n > 0 ? n : 0);
    if (n > 0 && fread(out.data(), 1, n, f) != (size_t)n) out.clear();
    fclose(f);
    return out;
}

// Validate parse_buffer against the manifest for one fixture.
static void test_parse(const NckFixture &fx) {
    auto buf = read_file(path(fx.full));
    CHECK(!buf.empty(), "fixture file read");
    if (buf.empty()) return;

    Card card;
    Status st = parse_buffer(buf.data(), buf.size(), card);
    CHECK(st == Status::Ok, fx.full);
    if (st != Status::Ok) {
        printf("  status=%s\n", status_str(st));
        return;
    }

    CHECK(card.name == fx.name, "name");
    CHECK(card.url == fx.url, "url");
    CHECK(card.message == fx.message, "message");
    CHECK(card.base_total_length == fx.base_total_length, "base_total_length");
    CHECK((int)card.assets.size() == fx.n_assets, "asset count");

    for (int i = 0; i < fx.n_assets && i < (int)card.assets.size(); i++) {
        const Asset &a = card.assets[i];
        const NckFixAsset &m = fx.assets[i];
        CHECK(a.type == m.type && a.flags == m.flags && a.subtype == m.subtype, "asset hdr");
        CHECK(a.offset == m.offset && a.length == m.length, "asset span");
        CHECK(a.crc == m.crc32, "asset crc field");
        CHECK(crc32(buf.data() + a.offset, a.length) == m.crc32, "asset bytes crc");
    }

    // display image is strip-on-share; share images are not.
    const Asset *disp = card.find(AssetType::DisplayJpeg);
    CHECK(disp && (disp->flags & kFlagStripOnShare), "display strip flag");
    for (const Asset *s : card.all(AssetType::ShareJpeg))
        CHECK((s->flags & kFlagStripOnShare) == 0, "share not stripped");
}

// open_file + read_asset round-trip from disk.
static void test_open_and_read(const NckFixture &fx) {
    Card card;
    Status st = open_file(path(fx.full).c_str(), card);
    CHECK(st == Status::Ok, "open_file");
    if (st != Status::Ok) return;
    CHECK(card.name == fx.name, "open_file name");
    CHECK(card.base_total_length == fx.base_total_length, "open_file base_total");

    const Asset *disp = card.find(AssetType::DisplayJpeg);
    CHECK(disp != nullptr, "open_file display present");
    if (disp) {
        std::vector<uint8_t> bytes(disp->length);
        st = read_asset(path(fx.full).c_str(), *disp, bytes.data(), bytes.size());
        CHECK(st == Status::Ok, "read_asset");
        CHECK(crc32(bytes.data(), bytes.size()) == disp->crc, "read_asset crc");
    }
}

// write_share_pdf must byte-match the golden share fixture.
static void test_write_share(const NckFixture &fx) {
    std::string tmp = "/tmp/nck_share_out.pdf";
    Status st = write_share_pdf(path(fx.full).c_str(), tmp.c_str());
    CHECK(st == Status::Ok, "write_share_pdf");
    if (st != Status::Ok) return;
    auto produced = read_file(tmp);
    auto golden = read_file(path(fx.share));
    CHECK(produced.size() == golden.size() && produced == golden, "share == golden");
    remove(tmp.c_str());

    // The produced share PDF re-parses, has no display, base_total_length 0.
    Card card;
    st = parse_buffer(golden.data(), golden.size(), card);
    CHECK(st == Status::Ok, "share re-parse");
    CHECK(card.find(AssetType::DisplayJpeg) == nullptr, "share has no display");
    CHECK(card.base_total_length == 0, "share base_total 0");
}

// name_glyphs blob parse + RLE decode, cross-checked to the known synthetic
// patterns the TS gen-fixtures emitted.
static void test_glyphs() {
    auto buf = read_file(path("glyphs.mnc.pdf"));
    Card card;
    CHECK(parse_buffer(buf.data(), buf.size(), card) == Status::Ok, "glyphs parse");
    const Asset *g = card.find(AssetType::NameGlyphs);
    CHECK(g != nullptr, "name_glyphs present");
    if (!g) return;

    GlyphSet set;
    Status st = parse_name_glyphs(buf.data() + g->offset, g->length, set);
    CHECK(st == Status::Ok, "parse_name_glyphs");
    CHECK(set.glyph_px == 48, "glyph_px 48");
    CHECK(set.glyphs.size() == 2, "glyph count 2");

    // Sorted by codepoint: 0x4E9C then 0x9B3C.
    const char *rows_4e9c[] = {"######", "...#..", "..#...", ".####.", "#....#", "#....#", ".####.", "......"};
    const char *rows_9b3c[] = {"..##..", ".#..#.", "######", "#....#", "#....#", "#....#", "#....#", "......"};
    struct Expect {
        uint32_t cp;
        const char **rows;
    } expects[] = {{0x4e9c, rows_4e9c}, {0x9b3c, rows_9b3c}};

    for (int gi = 0; gi < 2 && gi < (int)set.glyphs.size(); gi++) {
        const Glyph &gl = set.glyphs[gi];
        CHECK(gl.codepoint == expects[gi].cp, "glyph codepoint");
        CHECK(gl.box_w == 6 && gl.box_h == 8, "glyph box");
        std::vector<uint8_t> bits((gl.box_w * gl.box_h + 7) / 8);
        rle_decode(gl.rle, gl.rle_len, bits.data(), gl.box_w * gl.box_h);
        bool ok = true;
        for (int y = 0; y < gl.box_h; y++) {
            for (int x = 0; x < gl.box_w; x++) {
                int idx = y * gl.box_w + x;
                int bit = (bits[idx >> 3] >> (7 - (idx & 7))) & 1;
                int want = expects[gi].rows[y][x] == '#' ? 1 : 0;
                if (bit != want) ok = false;
            }
        }
        CHECK(ok, "glyph bitmap matches");
    }
}

// Malformed inputs must return an error, never crash (ASAN watches for OOB).
static void test_robustness() {
    Card card;
    CHECK(parse_buffer(nullptr, 0, card) == Status::BadArgument, "null");
    uint8_t tiny[4] = {1, 2, 3, 4};
    CHECK(parse_buffer(tiny, sizeof tiny, card) == Status::NotNckPdf, "too small");

    std::vector<uint8_t> junk(200, 0xab);
    CHECK(parse_buffer(junk.data(), junk.size(), card) == Status::NotNckPdf, "junk");

    auto buf = read_file(path("basic.mnc.pdf"));
    CHECK(parse_buffer(buf.data(), buf.size(), card) == Status::Ok, "baseline ok");

    // Truncate: drop the last few bytes -> trailer magic gone.
    CHECK(parse_buffer(buf.data(), buf.size() - 4, card) != Status::Ok, "truncated tail");

    // Corrupt a byte inside an asset payload -> CRC mismatch.
    auto corrupt = buf;
    corrupt[card.assets[0].offset] ^= 0xff;
    CHECK(parse_buffer(corrupt.data(), corrupt.size(), card) == Status::CrcMismatch, "asset crc");

    // Corrupt the footer index -> footer CRC mismatch.
    auto corrupt2 = buf;
    Card c2;
    parse_buffer(buf.data(), buf.size(), c2);  // need footer_offset; re-derive via trailer
    // flip a byte just before the trailer (inside the index region)
    corrupt2[corrupt2.size() - 24 - 1] ^= 0xff;
    CHECK(parse_buffer(corrupt2.data(), corrupt2.size(), c2) == Status::CrcMismatch, "footer crc");
}

int main(int argc, char **argv) {
    g_dir = argc > 1 ? argv[1] : "fixtures";

    for (int i = 0; i < kNckFixtureCount; i++) {
        test_parse(kNckFixtures[i]);
        test_open_and_read(kNckFixtures[i]);
        test_write_share(kNckFixtures[i]);
    }
    test_glyphs();
    test_robustness();

    if (failures) {
        printf("\n%d CHECK(s) failed\n", failures);
        return 1;
    }
    printf("all namecard_pdf tests passed\n");
    return 0;
}
