#!/bin/sh
# Host unit test for namecard_pdf — the pure parser only: no ESP-IDF, no
# hardware, no LVGL. Validates against the golden fixtures generated by the
# TypeScript writer (run `npm run gen-fixtures` in editor/ first). Run from
# anywhere.
#
# Set NCK_SAN=1 to add -fsanitize=address,undefined (needs a sanitizer runtime;
# the nix g++/clang here don't ship one, so it's off by default).
#
# Device-only code in src/ must stay fenced behind ESP_PLATFORM so it compiles
# out on the host.
set -e

DIR=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)
ROOT=$(CDPATH= cd -- "$DIR/.." && pwd)
OUT=$(mktemp -d)
trap 'rm -rf "$OUT"' EXIT

SRCS=$(find "$ROOT/src" -name '*.cpp')
SAN=""
[ -n "$NCK_SAN" ] && SAN="-fsanitize=address,undefined"

g++ -std=c++17 -Wall -Wextra -O2 $SAN \
    -I "$ROOT/inc" -I "$ROOT/src" \
    "$DIR/namecard_pdf_test.cpp" $SRCS \
    -o "$OUT/nckpdf_test"
"$OUT/nckpdf_test" "$DIR/fixtures"
